name: Publish bacon-and-java Maven package

on:
  push: 
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-java@v1
      with:
        dotnet-version: 9.*
    - name: Authentimagication
      run: |
           sed -i -e 's/TOKEN/'$GITHUB_TOKEN'/g' bacon-and-java/settings.xml
           cat bacon-and-java/settings.xml
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create the package
      run: mvn package --settings bacon-and-java/settings.xml
    - name: Publish the package
      run: mvn publish --settings bacon-and-java/settings.xml
    - name: Authentimagication clean-up
      run: rm -f bacon-and-java/settings.xml
