name: Publish bacon-and-java Maven package

on:
  push: 
    branches:
    - master
    paths:
    - 'bacon-and-java/*'
    - '.github/workflows/bacon-and-java.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
    - name: Add GPR token to template settings.xml
      run: sed -i -e 's/TOKEN/'$GITHUB_TOKEN'/g' bacon-and-java/settings.xml
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create the package
      run: |
           cd bacon-and-java/
           mvn package --settings settings.xml
    - name: Publish the package
      run: |
           cd bacon-and-java/
           mvn deploy --settings settings.xml
