name: Publish npm-bacon npm package

on:
  push: 
    branches:
    - master
    paths:
    - 'npm-bacon/*'
    - '.github/workflows/npm-bacon.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: Authentimagication
      run: echo //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN >> npm-bacon/.npmrc
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Publish the package
      run: npm publish
    - name: Authentimagication clean-up
      run: rm -f npm-bacon/.npmrc
