name: Publish bacon NuGet package

on:
  push:
    branches:
    - master
    paths:
    - 'nuget-bacon/*'
    - '.github/workflows/nuget-bacon.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: See directories
      run: |
           cd ../
           ls -lR
    - name: Setup .NET Core
      uses: infin8x/setup-dotnet@master 
      with:
        dotnet-version: 2.2.401
        source-url: https://nuget.pkg.github.com  
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Check config
      run: |
           cd ../
           ls -lR
    - name: Create the package
      run: dotnet pack nuget-bacon/ --configuration Release
    - name: Publish the package
      run: dotnet nuget push nuget-bacon/bin/Release/*.nupkg -s GPR
