name: Publish bacon NuGet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.401
    - name: Authentimagication
      run: sed -i -e 's/TOKEN/$GITHUB_TOKEN/g' nuget-bacon/nuget.template.config \
           mv nuget-bacon/nuget.template.config nuget-bacon/nuget.config
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create the package
      run: dotnet pack --configuration Release
    - name: Publish the package
      run: dotnet nuget push -s GPR nuget-bacon/bin/Release/*.nupkg
    - name: Authentimagication clean-up
      run: rm -f nuget.config
