name: Publish bacon NuGet package

on:
  push:
    branches:  
    - master
    paths:
    - 'nuget-bacon/*'
    - '.github/workflows/nuget-bacon.yml'

jobs:
  build:
    name: Publish bacon NuGet package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # , windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: infin8x/setup-dotnet@master 
      with:
        dotnet-version: 2.2.401
        source-url: https://nuget.pkg.github.com
    - name: Create the package
      run: | 
           cat /home/runner/work/nuget.config
           dotnet pack nuget-bacon/ --configuration Release
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - name: Publish the package
      run: dotnet nuget push nuget-bacon/bin/Release/*.nupkg -s GPR
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
