name: Publish bacon NuGet package

on:
  push:
    branches:
    - master
    paths:
    - 'nuget-bacon/*'
    - '.github/workflows/nuget-bacon.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: infin8x/setup-dotnet@infin8x/auth
      with:
        dotnet-version: 2.2.401
        source-url: https://nuget.pkg.github.com
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    # - name: Add GPR token to template nuget.config
    #   run: |
    #        sed -i -e 's/TOKEN/'$GITHUB_TOKEN'/g' nuget-bacon/nuget.template.config
    #        mv nuget-bacon/nuget.template.config nuget-bacon/nuget.config
    #   env:
    #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create the package
      run: dotnet pack nuget-bacon/ --configuration Release
    - name: Publish the package
      run: dotnet nuget push nuget-bacon/bin/Release/*.nupkg -s GPR
