name: Publish ruby-bacon gem

on:
  push:
    branches:
    - master
    paths:
    - 'ruby-bacon/*'
    - '.github/workflows/ruby-bacon.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.x
    - name: Add GPR token to template nuget.config
      run: |
           sed -i -e 's/TOKEN/'$GITHUB_TOKEN'/g' nuget-bacon/nuget.template.config
           mv nuget-bacon/nuget.template.config nuget-bacon/nuget.config
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create the package
      run: dotnet pack nuget-bacon/ --configuration Release
    - name: Publish the package
      run: dotnet nuget push nuget-bacon/bin/Release/*.nupkg -s GPR
